name: Docker Image Build and Push

on:
  workflow_dispatch:
    inputs:
      message:
        description: 'Message to print'
        required: false
        default: 'No message provided'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the repository
      uses: actions/checkout@v4  
    - run: |
          echo "Webhook Msg -- ${{ inputs.message }}"
    - name: Build the Docker image
      run: docker build . --file Dockerfile -t ${{ vars.DOCKERHUB_USERNAME }}/ise-exporter:latest
    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ vars.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Push Docker image - Latest
      run: docker push ${{ vars.DOCKERHUB_USERNAME }}/ise-exporter:latest
    - name: Logout from Docker Hub
      run: docker logout